# Site settings
title: Jana4U Blog
email: jana4u@seznam.cz
description: > # this means to ignore newlines until "baseurl:"
  Blog o všem možném.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jana4u.net" # the base hostname & protocol for your site
twitter_username: jana4u
github_username:  jana4u

# Build settings
markdown: kramdown
